apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-orders
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ecommerce-orders
  template:
    metadata:
      labels:
        app: ecommerce-orders
    spec:
      containers:
        - name: ecommerce-orders
          image: your-image-name:tag
          ports:
            - containerPort: 9090

---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-orders
spec:
  selector:
    app: ecommerce-orders
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7000
